title: Hello, world! I'm HuiZhu Zeng
description: > # this means to ignore newlines until "baseurl:"
  人嘛
  人生嘛
  生活嘛
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog 这个地方一定要小心！！！！！
url: "https://zenghuizhu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: HuiZhu Zeng # add your name
author-img: 2.jpg # add your photo
about-author: 不要贩卖焦虑！！！！！！！★,:*:‧\(￣▽￣)/‧:*‧°★* hi✿✿(。◕ᴗ◕。)✿✿ 没有过不去的坎！！！ # add description
social-twitter: ZHZ # add your Twitter handle
social-facebook: ZHZ # add your Facebook handle
social-github: zenghuizhu # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: 1428205702@qq.com # add your Email address

# Disqus
discus-identifier: zhz # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: BLOG
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
